import { OhmLabel } from './types.ts';

export interface DatabaseEntry {
  text: string;
  label: OhmLabel;
}

// Full BOOK OF NUANCE WORDS - OHM Resource Data
// GREEN (3 Ohm): Gap Fillers / Openers
// BLUE (5 Ohm): Sentence Frames
// RED (7 Ohm): Idioms & Nuance
// PINK (9 Ohm): Key Terms
export const KNOWN_PHRASES: DatabaseEntry[] = [
  // GREEN (3 Ohm - Gap Fillers / Openers)
  { text: "Từ bây giờ", label: "GREEN" },
  { text: "Từ giờ trở đi", label: "GREEN" },
  { text: "Tui không phiền kể cậu cái này", label: "GREEN" },
  { text: "Cả ngày hôm qua", label: "GREEN" },
  { text: "Sao phải vội thế", label: "GREEN" },
  { text: "Cậu vội cái gì", label: "GREEN" },
  { text: "Theo lẽ thường", label: "GREEN" },
  { text: "Logic mà nói", label: "GREEN" },
  { text: "Chịu", label: "GREEN" },
  { text: "Tui thua rồi đấy", label: "GREEN" },
  { text: "Đề đền bù cho cậu", label: "GREEN" },
  { text: "Tui không biết ai cho/tiêm cái đó vào đầu cậu", label: "GREEN" },
  { text: "Cám ơn vì đã mời tui", label: "GREEN" },
  { text: "Đừng có ngại/khách sáo", label: "GREEN" },
  { text: "Chẳng sớm thì muộn", label: "GREEN" },
  { text: "chẳng chóng thì chày", label: "GREEN" },
  { text: "Để rồi, cho đến một ngày", label: "GREEN" },
  { text: "Trên đường tới đây", label: "GREEN" },
  { text: "Tin tui đi", label: "GREEN" },
  { text: "Nếu tui mà là  cậu", label: "GREEN" },
  { text: "Nếu cậu mà là tui", label: "GREEN" },
  { text: "Nếu đó là sự thật", label: "GREEN" },
  { text: "Nếu đúng là vậy", label: "GREEN" },
  { text: "Tui đâu phải con nít", label: "GREEN" },
  { text: "Tui không có dễ bị dụ", label: "GREEN" },
  { text: "Nghĩ xem", label: "GREEN" },
  { text: "Nếu cậu thực sự nghĩ về cái đó", label: "GREEN" },
  { text: "(Cũng) dễ hiểu thôi", label: "GREEN" },
  { text: "Cậu thực sự không hiểu à", label: "GREEN" },
  { text: "Trùng hợp thế", label: "GREEN" },
  { text: "Lố bịch", label: "GREEN" },
  { text: "Hồi đầu năm nay", label: "GREEN" },
  { text: "Theo tui", label: "GREEN" },
  { text: "Quá đẹp", label: "GREEN" },
  { text: "Tuyệt vời", label: "GREEN" },
  { text: "Thành ra", label: "GREEN" },
  { text: "Do đó", label: "GREEN" },
  { text: "vì vậy", label: "GREEN" },
  { text: "vì lẽ đó", label: "GREEN" },
  { text: "Vô hình trung", label: "GREEN" },
  { text: "Bằng một cách nào đó", label: "GREEN" },
  { text: "Tuy nhiên", label: "GREEN" },
  { text: "Một cách miễn cưỡng", label: "GREEN" },
  { text: "Tui cho rằng", label: "GREEN" },
  { text: "Điều đó được cho là", label: "GREEN" },
  { text: "điều đó có nghĩa là", label: "GREEN" },
  { text: "Tui nghe lỏm được cái này", label: "GREEN" },
  { text: "Cái này cậu đừng nói ai nghe nha", label: "GREEN" },
  { text: "Trớ trêu thay", label: "GREEN" },
  { text: "Cậu có phải người Sài Gòn không dzậy", label: "GREEN" },
  { text: "Đừng hiểu nhầm ý tui nha", label: "GREEN" },
  { text: "Mới nhắc Tào Tháo", label: "GREEN" },
  { text: "Nói dzậy cũng nói", label: "GREEN" },
  { text: "Ở cái đất Sài Gòn này", label: "GREEN" },
  { text: "Mới đó mà đã 5 năm rồi", label: "GREEN" },
  { text: "Nhắc mới nhớ", label: "GREEN" },
  { text: "Đừng có mà lộn xộn nha", label: "GREEN" },
  { text: "Uả lộn", label: "GREEN" },
  { text: "Thế cơ à", label: "GREEN" },
  { text: "Hình như", label: "GREEN" },
  { text: "Có vẻ", label: "GREEN" },
  { text: "Hèn gì", label: "GREEN" },
  { text: "thảo nào", label: "GREEN" },
  { text: "chả trách", label: "GREEN" },
  { text: "ai dè", label: "GREEN" },
  { text: "Là saooo", label: "GREEN" },
  { text: "Nghear ổn đấy", label: "GREEN" },
  { text: "nghe okay đấy", label: "GREEN" },
  { text: "Báo cậu biết luôn", label: "GREEN" },
  { text: "Thiệttt", label: "GREEN" },
  { text: "Để chiii", label: "GREEN" },
  { text: "Ngày xửa ngày xưa", label: "GREEN" },
  { text: "Nói đi thì cũng phải nói lại", label: "GREEN" },
  { text: "Nói gì nói", label: "GREEN" },
  { text: "Đằng nào", label: "GREEN" },
  { text: "Hôm bữa", label: "GREEN" },
  { text: "Gì", label: "GREEN" },
  { text: "Cái gììì", label: "GREEN" },
  { text: "Đừng lo", label: "GREEN" },
  { text: "Đừng có lo", label: "GREEN" },
  { text: "Cùng lắm", label: "GREEN" },
  { text: "Cậu đang nói cái gì dzậy", label: "GREEN" },
  { text: "cậu nói gì kỳ dzậy", label: "GREEN" },
  { text: "Cậu nói dzậy mà nghe được à", label: "GREEN" },
  { text: "Bây giờ tôi hỏi cậu nè", label: "GREEN" },
  { text: "Nhìn nè", label: "GREEN" },
  { text: "Nghe nè", label: "GREEN" },
  { text: "Giờ cá không?!? Tôi dám cá", label: "GREEN" },
  { text: "Hổng ấy", label: "GREEN" },
  { text: "Nhìn vậy thôi", label: "GREEN" },
  { text: "còn lâu", label: "GREEN" },
  { text: "không đời nào", label: "GREEN" },
  { text: "Chuyện cũng lâu rồi", label: "GREEN" },
  { text: "Nói cậu biết luôn", label: "GREEN" },
  { text: "nói luôn với cậu", label: "GREEN" },
  { text: "Nói sao ta", label: "GREEN" },
  { text: "Nói thế nào nhỉ", label: "GREEN" },
  { text: "Tui cũng không biết nói sao nữa", label: "GREEN" },
  { text: "Làm hết hồn", label: "GREEN" },
  { text: "hết hồn hà", label: "GREEN" },
  { text: "Tui không có đùa nha", label: "GREEN" },
  { text: "tui không có giỡn à", label: "GREEN" },
  { text: "Nếu tui nhớ không nhầm thì", label: "GREEN" },
  { text: "Nếu tui nhớ đúng thì", label: "GREEN" },
  { text: "Lúc đó cậu nghĩ cái gì vậy", label: "GREEN" },
  { text: "Cậu hiểu hông", label: "GREEN" },
  { text: "Cậu hiểu ý tui hông", label: "GREEN" },
  { text: "Ý cậu sao", label: "GREEN" },
  { text: "cậu nghĩ sao", label: "GREEN" },
  { text: "Giờ vầy đi", label: "GREEN" },
  { text: "chuyện là dzầy", label: "GREEN" },
  { text: "Nói hay lắm", label: "GREEN" },
  { text: "Bây giờ tui hỏi cậu nè", label: "GREEN" },
  { text: "Thôi bỏ đi", label: "GREEN" },
  { text: "Không có gì", label: "GREEN" },
  { text: "Hài thiệt", label: "GREEN" },
  { text: "hài thiệt chứ", label: "GREEN" },
  { text: "Tào lao", label: "GREEN" },
  { text: "Nhảm nhí!.../ Xàm xí", label: "GREEN" },
  { text: "Chết bà", label: "GREEN" },
  { text: "chết cha", label: "GREEN" },
  { text: "Ngặt nỗi", label: "GREEN" },
  { text: "Chỉ là", label: "GREEN" },
  { text: "Khoannn", label: "GREEN" },
  { text: "Cũng hên", label: "GREEN" },
  { text: "cũng may", label: "GREEN" },
  { text: "Chuyện nhỏ mà", label: "GREEN" },
  { text: "chuyện gì lớn đâu", label: "GREEN" },
  { text: "Sao lâu vậy ta", label: "GREEN" },
  { text: "Tôi nói cậu nghe nè", label: "GREEN" },
  { text: "(Nói) không phải khoe chớ", label: "GREEN" },
  { text: "Bên cạnh đó", label: "GREEN" },
  { text: "Với lại", label: "GREEN" },
  { text: "với cả", label: "GREEN" },
  { text: "Cụ thể", label: "GREEN" },
  { text: "Cậu nói vậy đâu được", label: "GREEN" },
  { text: "Không lâu sao đó", label: "GREEN" },
  { text: "Xui thay", label: "GREEN" },
  { text: "Đen thay", label: "GREEN" },
  { text: "Mấy nay/Bữa giờ/Dạo này/ nghe bảo", label: "GREEN" },
  { text: "May thay", label: "GREEN" },
  { text: "Ai lại", label: "GREEN" },
  { text: "Ai lại không", label: "GREEN" },
  { text: "Từ góc độ của tui", label: "GREEN" },
  { text: "Từ góc nhìn của tui", label: "GREEN" },
  { text: "Nói cách khác", label: "GREEN" },
  { text: "Suy cho cùng", label: "GREEN" },
  { text: "cuối cùng", label: "GREEN" },
  { text: "Thử đi", label: "GREEN" },
  { text: "Tui xạo câu chi", label: "GREEN" },
  { text: "Tui lừa cậu làm gì", label: "GREEN" },
  { text: "Mới đó mà đã 3 năm rồi", label: "GREEN" },
  { text: "Về cơ bản", label: "GREEN" },
  { text: "cơ bản mà nói", label: "GREEN" },
  { text: "Thôi thôi tui xin", label: "GREEN" },
  { text: "tui lạy cậu", label: "GREEN" },
  { text: "Okay tui thua", label: "GREEN" },
  { text: "okay tui thua rồi đấy", label: "GREEN" },
  { text: "Thôi đừng có chọc/ghẹo tui nữa", label: "GREEN" },
  { text: "Dần dần theo thời gian", label: "GREEN" },
  { text: "dần dà", label: "GREEN" },
  { text: "lâu dần", label: "GREEN" },
  { text: "Có trời biết", label: "GREEN" },
  { text: "Hồi đó", label: "GREEN" },
  { text: "Hồi cấp ba", label: "GREEN" },
  { text: "Lẹ lên", label: "GREEN" },
  { text: "nhanh lên", label: "GREEN" },
  { text: "Trong suốt 10 năm", label: "GREEN" },
  { text: "Ngày này năm sau", label: "GREEN" },
  { text: "Thế thì cậu nhầm", label: "GREEN" },
  { text: "Dẫu vậy", label: "GREEN" },
  { text: "Mặc dù vậy", label: "GREEN" },
  { text: "Hay chính xác hơn", label: "GREEN" },
  { text: "Xém nữa", label: "GREEN" },
  { text: "xém chết", label: "GREEN" },
  { text: "Thấy chưa", label: "GREEN" },
  { text: "Sáng mắt ra chưa", label: "GREEN" },
  { text: "Thề luôn", label: "GREEN" },
  { text: "Tui thề", label: "GREEN" },
  { text: "Thề có trời", label: "GREEN" },
  { text: "Cứ từ từ", label: "GREEN" },
  { text: "không gấp", label: "GREEN" },
  { text: "Nghĩ kỹ chưa", label: "GREEN" },
  { text: "Thíệtttt", label: "GREEN" },
  { text: "Cậu giúp tui chuyện được không", label: "GREEN" },
  { text: "Tính ra", label: "GREEN" },
  { text: "Hóa ra", label: "GREEN" },
  { text: "Tóm lại", label: "GREEN" },
  { text: "Ngược lại", label: "GREEN" },
  { text: "Mừng cho cậu", label: "GREEN" },
  { text: "Lần này tui tha", label: "GREEN" },
  { text: "lần này tui bỏ qua", label: "GREEN" },
  { text: "Bất thình lình", label: "GREEN" },
  { text: "Tự dưng", label: "GREEN" },
  { text: "Phải vậy chớ", label: "GREEN" },
  { text: "Cậu biết sao không", label: "GREEN" },
  { text: "Mới nãy", label: "GREEN" },
  { text: "Cậu biết tin gì chưa", label: "GREEN" },
  { text: "Cậu nghe tin gì chưa", label: "GREEN" },
  { text: "Có tin tức gì không", label: "GREEN" },
  { text: "Tui e là", label: "GREEN" },
  { text: "Có một thứ mà tui quên báo cậu trước", label: "GREEN" },
  { text: "Nản thiệt chứ", label: "GREEN" },
  { text: "Nản thiệt", label: "GREEN" },
  { text: "Chán đời thiệt", label: "GREEN" },
  { text: "Đúng nghĩa thì", label: "GREEN" },
  { text: "đúng ra thì", label: "GREEN" },
  { text: "Tin hay không thì tùy", label: "GREEN" },
  { text: "Để tui nhắc cho cậu nhớ", label: "GREEN" },
  { text: "Nói nhỏ thôi", label: "GREEN" },
  { text: "Nói khẽ thôi", label: "GREEN" },
  { text: "Nếu cậu để ý", label: "GREEN" },
  { text: "Cậu quên rồi à", label: "GREEN" },
  { text: "Quan trọng hơn", label: "GREEN" },
  { text: "Có một lần như vầy", label: "GREEN" },
  { text: "Như tui đã nói", label: "GREEN" },
  { text: "Tôi cũng không chắc", label: "GREEN" },
  { text: "Cái vấn đề là", label: "GREEN" },
  { text: "Vấn đề là", label: "GREEN" },
  { text: "Còn phải hỏi", label: "GREEN" },
  { text: "Vậy cũng hỏi", label: "GREEN" },
  { text: "Chứ còn gì nữa", label: "GREEN" },
  { text: "Đương nhiên", label: "GREEN" },
  { text: "Nói vô đề", label: "GREEN" },
  { text: "nói vào trọng tâm", label: "GREEN" },
  { text: "Bớt nói xàm đi", label: "GREEN" },
  { text: "(Khi) nói về", label: "GREEN" },
  { text: "Khi nói đến chuyện", label: "GREEN" },
  { text: "Tui biết ngay mà", label: "GREEN" },
  { text: "Uả", label: "GREEN" },
  { text: "Báo trước nha", label: "GREEN" },
  { text: "Để tui báo trước với cậu", label: "GREEN" },
  { text: "Trong những lúc như vầy", label: "GREEN" },
  { text: "Có vậy thôi đó", label: "GREEN" },
  { text: "Rồi đó", label: "GREEN" },
  { text: "Như cũ", label: "GREEN" },
  { text: "như thường lệ", label: "GREEN" },
  { text: "như mọi khi", label: "GREEN" },
  { text: "Tui cứ thắc mắc", label: "GREEN" },
  { text: "Trong lúc đó", label: "GREEN" },
  { text: "trong khi đó", label: "GREEN" },
  { text: "Sao lại không", label: "GREEN" },
  { text: "Sao lại là tui", label: "GREEN" },
  { text: "Thôiiii...,/ thôi màaaaa", label: "GREEN" },
  { text: "Cậu biết rồi đó", label: "GREEN" },
  { text: "Như cậu cũng biết rồi đó", label: "GREEN" },
  { text: "Tui biết cậu quá", label: "GREEN" },
  { text: "Tui còn lạ gì cậu", label: "GREEN" },
  { text: "Cậu biết tui mà", label: "GREEN" },
  { text: "Cậu biết tính tui rồi đấy", label: "GREEN" },
  { text: "Cơ bản mà nói thì", label: "GREEN" },
  { text: "Nói đại đi", label: "GREEN" },
  { text: "Một cách nào đó", label: "GREEN" },
  { text: "Ở thời điểm hiện tại", label: "GREEN" },
  { text: "Hiện tại", label: "GREEN" },
  { text: "Một lúc nào đó", label: "GREEN" },
  { text: "Vào một thời điểm nào đó", label: "GREEN" },
  { text: "... mọi thời đại", label: "GREEN" },
  { text: "Không như cậu", label: "GREEN" },
  { text: "Cũng như cậu", label: "GREEN" },
  { text: "Hình như cậu đang tìm cái này", label: "GREEN" },
  { text: "Sao không ai nói tui biết trước", label: "GREEN" },
  { text: "Sao giờ mới nói", label: "GREEN" },
  { text: "Chuyện dài lắm", label: "GREEN" },
  { text: "Tui không có đang cố nói quá lên", label: "GREEN" },
  { text: "Tui không có nổ đâu", label: "GREEN" },
  { text: "Có một câu nói nổi tiếng nói rằng:", label: "GREEN" },
  { text: "Để tui nói vầy đi", label: "GREEN" },
  { text: "để tui nói vầy cho dễ hiểu", label: "GREEN" },
  { text: "Nghe bảo", label: "GREEN" },
  { text: "nghe đồn", label: "GREEN" },
  { text: "Nghe như kiểu", label: "GREEN" },
  { text: "Trông như kiểu", label: "GREEN" },
  { text: "Để tui ngắt lời cậu ngay đó", label: "GREEN" },
  { text: "Xin phép ngắt lời cậu ngay đó", label: "GREEN" },
  { text: "Hổng chừng", label: "GREEN" },
  { text: "Mơ đi cưng", label: "GREEN" },
  { text: "Dù gì", label: "GREEN" },
  { text: "Dù sao thì", label: "GREEN" },
  { text: "Thú nhận đi", label: "GREEN" },
  { text: "Thừa nhận đi", label: "GREEN" },
  { text: "Thì để tui nói xong đã", label: "GREEN" },
  { text: "Thì đừng có nhảy vô họng tui", label: "GREEN" },
  { text: "Đơn giản mà nói thì", label: "GREEN" },
  { text: "Nói một cách đơn giản thì", label: "GREEN" },
  { text: "Đặc biệt là khi", label: "GREEN" },
  { text: "Đầu tiên và trên hết", label: "GREEN" },
  { text: "Trước hết", label: "GREEN" },
  { text: "Hậu quả là", label: "GREEN" },
  { text: "Đổi lại", label: "GREEN" },
  { text: "Thoạt nhìn", label: "GREEN" },
  { text: "Có chuyện này tui muốn nói với cậu", label: "GREEN" },
  { text: "Nói chung", label: "GREEN" },
  { text: "Nhìn chung", label: "GREEN" },
  { text: "Không thể phủ nhận rằng", label: "GREEN" },
  { text: "Sai bét", label: "GREEN" },
  { text: "Cậu tiếc cái gì", label: "GREEN" },
  { text: "Để cậu không còn lăn tăn", label: "GREEN" },
  { text: "Để cậu không phải nghĩ ngợi", label: "GREEN" },
  { text: "Nay cậu (bị làm) sao dzậy", label: "GREEN" },
  { text: "Cậu vẫn không hiểu à", label: "GREEN" },
  { text: "Không biết là hên hay xui", label: "GREEN" },
  { text: "Lúc đó", label: "GREEN" },
  { text: "Cuối năm nay", label: "GREEN" },
  { text: "Từ hôm qua giờ", label: "GREEN" },
  { text: "Và trên/hơn hết", label: "GREEN" },
  { text: "Hết hồn", label: "GREEN" },
  { text: "hết cả hồn", label: "GREEN" },
  { text: "Giật bắn người", label: "GREEN" },
  { text: "Không biết hên hay xui", label: "GREEN" },
  { text: "Thực sự mà nói thì", label: "GREEN" },
  { text: "Thực sự thì", label: "GREEN" },
  { text: "Chẳng phải tui đã nói cậu rồi sao", label: "GREEN" },
  { text: "Đúng như tui đoán", label: "GREEN" },
  { text: "Cậu nhìn vậy là ý gì", label: "GREEN" },
  { text: "Lúc đó tui nghĩ bụng", label: "GREEN" },
  { text: "Nghiiii lắm nha", label: "GREEN" },
  { text: "Đáng nghi lắm nha", label: "GREEN" },
  { text: "Sự thật đắng lòng", label: "GREEN" },
  { text: "Thô nhưng thật", label: "GREEN" },
  { text: "Chính mắt tui thấy mà", label: "GREEN" },
  { text: "Để coi", label: "GREEN" },
  { text: "Đừng có ngây thơ thế", label: "GREEN" },
  { text: "Cậu xem tui là loại người nào", label: "GREEN" },
  { text: "Bấy giờ cậu có xin lỗi hay là không", label: "GREEN" },
  { text: "Cậu cứ nghĩ thử xem", label: "GREEN" },
  { text: "Nếu không", label: "GREEN" },
  { text: "Nói chuyện quề dốn", label: "GREEN" },
  { text: "Thì tui đã nói nãy giờ đóooo", label: "GREEN" },
  { text: "Xong phim", label: "GREEN" },
  { text: "Giờ có cho tiền tui cũng hông dám", label: "GREEN" },
  { text: "Thôi tui sợ lắm", label: "GREEN" },
  { text: "Khai ra mau", label: "GREEN" },
  { text: "Khai ra lẹ lên", label: "GREEN" },
  { text: "Đó giờ tui mới biết luôn ó", label: "GREEN" },
  { text: "Không lẽ nó nói gì cậu cũng tin", label: "GREEN" },
  { text: "Sao cậu không hỏi tui (1) tiếng", label: "GREEN" },
  { text: "Nếu cậu có chuẩn bị (trước)", label: "GREEN" },
  { text: "Vừa lòng cậu chưa", label: "GREEN" },
  { text: "Bình tĩnh, có phải tận thế đâu", label: "GREEN" },
  { text: "Từ từ chuyện đâu còn có đó", label: "GREEN" },
  { text: "Trong mắt tui", label: "GREEN" },
  { text: "Cậu có bao giờ từng nghĩ", label: "GREEN" },
  { text: "tự hỏi", label: "GREEN" },
  { text: "Hết 9 trên 10 lần", label: "GREEN" },
  { text: "Không cần phí hơi/lời", label: "GREEN" },
  { text: "Ở một mức độ nào đó", label: "GREEN" },
  { text: "Lại nữaaa", label: "GREEN" },
  { text: "Nữaaa", label: "GREEN" },
  { text: "Yên chí", label: "GREEN" },
  { text: "Yên tâm", label: "GREEN" },
  { text: "Theo như tui biết", label: "GREEN" },
  { text: "Nào ngờ", label: "GREEN" },
  { text: "Ai ngờ", label: "GREEN" },
  { text: "Từ tận đáy lòng", label: "GREEN" },
  { text: "Lý thuyết mà nói", label: "GREEN" },
  { text: "Về lý thuyết", label: "GREEN" },
  { text: "Nhân tiện", label: "GREEN" },
  { text: "Để tui nói luôn", label: "GREEN" },
  { text: "Để tui nói thẳng nha", label: "GREEN" },
  { text: "Lạ thiệt", label: "GREEN" },
  { text: "Kỳ lạ", label: "GREEN" },
  { text: "Bằng mọi giá tui sẽ", label: "GREEN" },
  { text: "dẫu sao thì", label: "GREEN" },
  { text: "Phiền thiệt", label: "GREEN" },
  { text: "Thiệt là phiền toái", label: "GREEN" },
  { text: "Đừng có mà mách lẻo ai", label: "GREEN" },
  { text: "Đừng kể ai đấy", label: "GREEN" },
  { text: "Trong số mọi người đang ngồi đây", label: "GREEN" },
  { text: "Chắc chắn rồi", label: "GREEN" },
  { text: "Đúng", label: "GREEN" },
  { text: "Phải", label: "GREEN" },
  { text: "Cái đó là giả bộ thôi", label: "GREEN" },
  { text: "Trong 20 năm vừa qua", label: "GREEN" },
  { text: "Tui từng bị hiểu lầm rất nhiều", label: "GREEN" },
  { text: "Cám ơn đã tin tưởng tui", label: "GREEN" },
  { text: "Tui sẽ không làm cậu thất vọng", label: "GREEN" },
  { text: "Nếu cái đó đúng", label: "GREEN" },
  { text: "Nếu nó đúng là vậy", label: "GREEN" },
  { text: "Ít nhất", label: "GREEN" },
  { text: "Ai biểu!... (chi)", label: "GREEN" },
  { text: "Cậu biết điều đó nghĩa là gì không", label: "GREEN" },
  { text: "Cậu biết cái đó nghĩa là sao không", label: "GREEN" },
  { text: "Chưa kể đến việc", label: "GREEN" },
  { text: "Tôi e rằng", label: "GREEN" },
  { text: "Tui không có muốn nói xui", label: "GREEN" },
  { text: "Cố lên", label: "GREEN" },
  { text: "Kiên trì lên", label: "GREEN" },
  { text: "Có gì thông cảm cho tui nha", label: "GREEN" },
  { text: "WOWWW", label: "GREEN" },
  { text: "Tương tự vậy", label: "GREEN" },
  { text: "Thẳng thắn mà nói", label: "GREEN" },
  { text: "Dù muốn dù không", label: "GREEN" },
  { text: "Ê cậu đi xa quá rồi đấy", label: "GREEN" },
  { text: "Chơi thì chơi! sợ gì", label: "GREEN" },
  { text: "Dù là vô tình hay cố ý", label: "GREEN" },
  { text: "Lỗi tui", label: "GREEN" },
  { text: "Thích thì chiều", label: "GREEN" },
  { text: "Cậu tự hiểu đi", label: "GREEN" },
  { text: "Sao cứ phải làm to chuyện ra", label: "GREEN" },
  { text: "Sao phải xoắn", label: "GREEN" },
  { text: "Sao phải nghiêm túc thế", label: "GREEN" },
  { text: "Sao cậu không nói gì nữa đi", label: "GREEN" },
  { text: "Sao im lặng thế", label: "GREEN" },
  { text: "Giờ đến lượt tui", label: "GREEN" },
  { text: "Còn khuya nhaaaa", label: "GREEN" },
  { text: "Bỏ liền cái suy nghĩ đó đi nha", label: "GREEN" },
  { text: "Tưởng gì", label: "GREEN" },
  { text: "Tường thế nào", label: "GREEN" },
  { text: "Đời là dzậy đó", label: "GREEN" },
  { text: "Cách đây 3 ngày", label: "GREEN" },
  { text: "3 ngày vừa rồi", label: "GREEN" },
  { text: "Trong 3 ngày tới", label: "GREEN" },
  { text: "Hồi đầu", label: "GREEN" },
  { text: "Nhưng khi tui nhìn lại tất cả", label: "GREEN" },

  // BLUE (5 Ohm - Sentence Frames)
  { text: "Cậu nên nhớ rằng", label: "BLUE" },
  { text: "Nếu cậu mà biết nghĩ thì cậu đâu có", label: "BLUE" },
  { text: "Tui thực sự không có đủ thời gian để", label: "BLUE" },
  { text: "Tui không hiểu cậu lấy đâu ra nhiều tiền đến thế để", label: "BLUE" },
  { text: "Cậu có phiền nếu tui", label: "BLUE" },
  { text: "Để tui chỉ cho cậu thấy tại sao", label: "BLUE" },
  { text: "Tui nghĩ cậu nên hỏi ý... trước đi", label: "BLUE" },
  { text: "Không thể có cái chuyện", label: "BLUE" },
  { text: "Cậu nói cứ như kiểu", label: "BLUE" },
  { text: "Cậu không thấy tụi nó cứ... à", label: "BLUE" },
  { text: "Cậu thì lúc nào cũng", label: "BLUE" },
  { text: "... thì có gì mà đáng sợ", label: "BLUE" },
  { text: "Tui chẳng hiểu sao cậu cứ", label: "BLUE" },
  { text: "Tui thấy nó khá là", label: "BLUE" },
  { text: "Họ nhờ tui", label: "BLUE" },
  { text: "Trên mạng bây giờ tràn ngập", label: "BLUE" },
  { text: "Tui thực sự không biết cách để", label: "BLUE" },
  { text: "Tôi không thèm cái", label: "BLUE" },
  { text: "Mỗi khi..., tui lại", label: "BLUE" },
  { text: "Có tổng cộng", label: "BLUE" },
  { text: "Nó quá là liều để", label: "BLUE" },
  { text: "Tui không ngờ", label: "BLUE" },
  { text: "Tui đang nghĩ liệu có phải vì", label: "BLUE" },
  { text: "Chúng ta không có cửa", label: "BLUE" },
  { text: "Ai/đứa nào chịu trách nhiệm", label: "BLUE" },
  { text: "Đây là lần cuối cùng tui", label: "BLUE" },
  { text: "Họ cho chúng ta 3 ngày để", label: "BLUE" },
  { text: "Cậu có 3 phút để", label: "BLUE" },
  { text: "Nếu cậu đang... thì cậu nhầm", label: "BLUE" },
  { text: "Trở thành... đâu có khó đến vậy", label: "BLUE" },
  { text: "Đừng bao giờ cố", label: "BLUE" },
  { text: "Chỉ có một và chỉ một", label: "BLUE" },
  { text: "Đó là mối tương quan giữa... và", label: "BLUE" },
  { text: "Cậu thừa biết là", label: "BLUE" },
  { text: "Cậu có sợ... không", label: "BLUE" },
  { text: "Chúng ta chẳng biết gì nhiều về", label: "BLUE" },
  { text: "Làm sao để biến... thành", label: "BLUE" },
  { text: "Wow, cậu quả là", label: "BLUE" },
  { text: "Cậu vẫn còn..., phải không", label: "BLUE" },
  { text: "Tui chỉ nói vậy với hi vọng rằng", label: "BLUE" },
  { text: "Cậu gọi cái này là... à", label: "BLUE" },
  { text: "Trong quá khứ tui từng nghĩ", label: "BLUE" },
  { text: "Ai xúi cậu", label: "BLUE" },
  { text: "Nếu họ chỉ là bạn bè thì họ đâu có", label: "BLUE" },
  { text: "Nhanh quá ha mới đó mà", label: "BLUE" },
  { text: "Sao cậu lại có thể", label: "BLUE" },
  { text: "... coi sao được", label: "BLUE" },
  { text: "... còn ra cái thể thống gì nữa", label: "BLUE" },
  { text: "Có vậy thôi mà cũng", label: "BLUE" },
  { text: "Nhìn vậy thôi chớ... đó nha", label: "BLUE" },
  { text: "Đâu, nó đâu có... dữ dzậy", label: "BLUE" },
  { text: "Cậu không thấy tui đang.... à", label: "BLUE" },
  { text: "Ý cậu là tui... à", label: "BLUE" },
  { text: "ý cậu đang nói là tui.... á hả", label: "BLUE" },
  { text: "Không có cậu là tui... rồi", label: "BLUE" },
  { text: "Không biết cậu sao chứ tui thì", label: "BLUE" },
  { text: "Cậu mà... một lần nữa thì đừng có trách", label: "BLUE" },
  { text: "Nói xin lỗi chớ", label: "BLUE" },
  { text: "nói cậu đừng để bụng", label: "BLUE" },
  { text: "Cậu... bộ chết hả", label: "BLUE" },
  { text: "Đừng nói tui là cậu... đó nha", label: "BLUE" },
  { text: "Uả, tui không có được (phép)... hả", label: "BLUE" },
  { text: "Cậu nói vậy chẳng khác nào", label: "BLUE" },
  { text: "Nè, tui nói vậy không có nghĩa là", label: "BLUE" },
  { text: "Xin lỗi giờ tui không có hứng", label: "BLUE" },
  { text: "... cái kiểu gì mà", label: "BLUE" },
  { text: "Ê cậu không được... nha", label: "BLUE" },
  { text: "Bất kể nó có... đến thế nào đi nữa, đó vẫn là", label: "BLUE" },
  { text: "Chứ cậu nghĩ tại sao tui lại", label: "BLUE" },
  { text: "Ai cho phép cậu", label: "BLUE" },
  { text: "Tui lấy... để chi", label: "BLUE" },
  { text: "Cậu không có quyền... ở đây, okay", label: "BLUE" },
  { text: "Tui không thể chịu nổi cái cảm giác", label: "BLUE" },
  { text: "Cũng lâu rồi từ khi", label: "BLUE" },
  { text: "... nói cũng có lý đấy", label: "BLUE" },
  { text: "Nhỡ... thì sao", label: "BLUE" },
  { text: "Cậu tốn bao lâu để", label: "BLUE" },
  { text: "Không tin thì cậu đi mà hỏi", label: "BLUE" },
  { text: ".... thì liên quan gì đến tui", label: "BLUE" },
  { text: "Tui biết tui còn khuya mới... bằng cậu", label: "BLUE" },
  { text: "Điều gì làm cậu tin rằng", label: "BLUE" },
  { text: "Tôi thực sự không nỡ", label: "BLUE" },
  { text: "Tui từng có", label: "BLUE" },
  { text: "Tui từng một lần", label: "BLUE" },
  { text: "Càng lớn tui càng nhận ra", label: "BLUE" },
  { text: "Tui nhớ là đã bị... rồi", label: "BLUE" },
  { text: "Có..., làm thấy ghê", label: "BLUE" },
  { text: "Tui chỉ nói vậy vì... thôi", label: "BLUE" },
  { text: "Làm sao cậu biết", label: "BLUE" },
  { text: "Cái điều quan trọng là", label: "BLUE" },
  { text: "Quan trọng nhất là", label: "BLUE" },
  { text: "Tui rất biết ơn vì", label: "BLUE" },
  { text: "Tôi dành rất nhiều thời gian cho việc", label: "BLUE" },
  { text: "Tui không thích... chút nào hết", label: "BLUE" },
  { text: "Điều gì làm cậu", label: "BLUE" },
  { text: "Nghe thì có vẻ lạ nhưng mà", label: "BLUE" },
  { text: "nghe thì có vẻ khó tin nhưng mà", label: "BLUE" },
  { text: "Cậu làm gì có gan để", label: "BLUE" },
  { text: "cậu chẳng có gan để... đâu", label: "BLUE" },
  { text: "Cậu có cái ví dụ nào cụ thể cho... không", label: "BLUE" },
  { text: "Tui mà biết trước, tui đã", label: "BLUE" },
  { text: "Không quan trọng nó... đến cỡ nào", label: "BLUE" },
  { text: "Tất cả mọi người ai cũng đều... trừ tui", label: "BLUE" },
  { text: "Tất cả những gì tui có thể làm cho cậu là", label: "BLUE" },
  { text: "Ê, tui mới là cái đứa phải... đây nè", label: "BLUE" },
  { text: "Cậu càng cố gắng, cuộc chơi sẽ càng", label: "BLUE" },
  { text: "... đều quy về cùng một chuyện cả thôi", label: "BLUE" },
  { text: "... bị sao vậy", label: "BLUE" },
  { text: "Tui lấy đâu ra cái... đây", label: "BLUE" },
  { text: "Có một chuyện tui chưa từng nói cậu", label: "BLUE" },
  { text: "Sao cậu cứ... thế nhỉ", label: "BLUE" },
  { text: "Cậu đâu nhất thiết phải", label: "BLUE" },
  { text: "Lúc đó tui đang", label: "BLUE" },
  { text: "Nhiều khi tui cũng không biết", label: "BLUE" },
  { text: "Cậu nghĩ thử coi, nếu bây giờ", label: "BLUE" },
  { text: "Tui có thể đồng ý mọi thứ ngoại trừ", label: "BLUE" },
  { text: "trừ", label: "BLUE" },
  { text: "Rồi họ... chưa", label: "BLUE" },
  { text: "Cậu phải... thì mới... được", label: "BLUE" },
  { text: "... đang dần", label: "BLUE" },
  { text: "Đã bảo... mà", label: "BLUE" },
  { text: "đã bảo cậu... mà", label: "BLUE" },
  { text: "Sao cậu lúc nào cũng", label: "BLUE" },
  { text: "Trời đẹp thế này mà không... thì quả là phí phạm", label: "BLUE" },
  { text: "... thì đã sao", label: "BLUE" },
  { text: "... thì đã bị làm sao", label: "BLUE" },
  { text: "Cậu không có được (phép)... nha", label: "BLUE" },
  { text: "Ai mà hổng biết", label: "BLUE" },
  { text: "Ai cũng biết", label: "BLUE" },
  { text: "Tui thắc mắc liệu", label: "BLUE" },
  { text: "Tốt hơn là cậu nên", label: "BLUE" },
  { text: "cậu tốt hơn nên", label: "BLUE" },
  { text: "Sao cậu không thử", label: "BLUE" },
  { text: "Tui tốn cả một năm trời chỉ để", label: "BLUE" },
  { text: "Cậu không nhận ra... à", label: "BLUE" },
  { text: "Cậu có biết tôi đã phải.... không", label: "BLUE" },
  { text: "Điều tui đang muốn nói là", label: "BLUE" },
  { text: "Ý tui là", label: "BLUE" },
  { text: "Tui chưa bao giờ", label: "BLUE" },
  { text: "tui chưa từng bao giờ", label: "BLUE" },
  { text: "Nếu cậu... thì cứ tự nhiên", label: "BLUE" },
  { text: "Nếu cậu... thì cứ thoải mái", label: "BLUE" },
  { text: "Cậu có bao giờ", label: "BLUE" },
  { text: "Cậu có từng... chưa", label: "BLUE" },
  { text: "Có cách nào tui có thể... không", label: "BLUE" },
  { text: "Nếu không có cậu chắc tui đã", label: "BLUE" },
  { text: "Đã nói cậu... rồi mà", label: "BLUE" },
  { text: "Ai bắt cậu", label: "BLUE" },
  { text: "Đứa nào bắt cậu", label: "BLUE" },
  { text: "Cậu có để ý... không", label: "BLUE" },
  { text: "Tui còn khuya mới", label: "BLUE" },
  { text: "Nếu cậu là người Việt chắc chắn cậu biết", label: "BLUE" },
  { text: "Ê cậu... xong chưa", label: "BLUE" },
  { text: "Ê cậu xong cái... chưa", label: "BLUE" },
  { text: "Tui đâu có sự lựa chọn nào khác ngoài việc", label: "BLUE" },
  { text: "Sao cứ hở ra là cậu lại... dzậy", label: "BLUE" },
  { text: "Để tui thử... xem sao", label: "BLUE" },
  { text: "Cậu nói... Cậu có bằng chứng không", label: "BLUE" },
  { text: "Cậu có sẵn lòng... không", label: "BLUE" },
  { text: "Đó chính là lý do mà", label: "BLUE" },
  { text: "đó cũng là lý do mà", label: "BLUE" },
  { text: "Thực ra đây là lần đầu tôi", label: "BLUE" },
  { text: "Cậu làm như ai cũng... không bằng", label: "BLUE" },
  { text: "Cậu phải hiểu là", label: "BLUE" },
  { text: "Có cái... mà khoe quài", label: "BLUE" },
  { text: "Uả tui không... thì tui ngồi đây chi", label: "BLUE" },
  { text: "Cậu nói thì hay lắm sao cậu không tự đi mà", label: "BLUE" },
  { text: "Thế nào mai tụi nó cũng... cho mà xem", label: "BLUE" },
  { text: "Ê đừng có lôi... vô đây nha", label: "BLUE" },
  { text: "Từ đó tui không bao giờ", label: "BLUE" },
  { text: "Ngay từ đầu tui đã biết", label: "BLUE" },
  { text: "Một khi cậu đã quyết định", label: "BLUE" },
  { text: "Cậu (làm) xong... chưa", label: "BLUE" },
  { text: "Cứ 10 người thì có 1 người", label: "BLUE" },
  { text: "Ai rồi cũng sẽ... thôi", label: "BLUE" },
  { text: "Tui tin rằng không ai trong chúng ta", label: "BLUE" },
  { text: "Ai bảo cậu là", label: "BLUE" },
  { text: "Đứa nào nói cậu", label: "BLUE" },
  { text: "Thật là vinh dự cho tui để", label: "BLUE" },
  { text: "Đố bạn", label: "BLUE" },
  { text: "Điều gì làm cậu nghĩ", label: "BLUE" },
  { text: "Sẵn tiện cậu nhắc đến chuyện đó", label: "BLUE" },
  { text: "Ai ai cũng..., kể cả tui", label: "BLUE" },
  { text: "Khổ ghê, tui đã bảo", label: "BLUE" },
  { text: "Quả là một", label: "BLUE" },
  { text: "Đáng lẽ ra giờ này là", label: "BLUE" },
  { text: "Cậu không thấy tui đang... à", label: "BLUE" },
  { text: "Cậu nghĩ làm vậy là họ sẽ... à", label: "BLUE" },
  { text: "Mấy chuyện này thường tình mà", label: "BLUE" },
  { text: "Mấy chuyện này xảy ra hoài ấy mà", label: "BLUE" },
  { text: "Sao cậu cứ", label: "BLUE" },
  { text: "Từ khi nào mà cậu", label: "BLUE" },
  { text: "Ngày nay có rất nhiều", label: "BLUE" },
  { text: "Tui là fan ruột của", label: "BLUE" },
  { text: "... thì có chết ai đâu", label: "BLUE" },
  { text: "... thì có sao đâu", label: "BLUE" },
  { text: "Chắc chắn là cậu đang nghĩ", label: "BLUE" },
  { text: "Hẳn là cậu đang nghĩ", label: "BLUE" },
  { text: "Chắc hẳn cậu đang nghĩ", label: "BLUE" },
  { text: "Tui có nằm mơ cũng không bao giờ nghĩ", label: "BLUE" },
  { text: "Tôi ước ngày nào đó tui có thể", label: "BLUE" },
  { text: "Rồi cậu tính trì hoãn... đến khi nào", label: "BLUE" },
  { text: "Tui đoán họ sắp", label: "BLUE" },
  { text: "Nếu cậu có chuẩn bị/tìm hiểu, cậu sẽ biết", label: "BLUE" },
  { text: "Để tui đoán xem tui có hiểu đúng ý cậu không", label: "BLUE" },
  { text: "Cậu đang cố tình... đấy à", label: "BLUE" },
  { text: "Ai dạy cậu... thế này", label: "BLUE" },
  { text: "Ai chỉ cậu... thế này", label: "BLUE" },
  { text: "Giờ này năm sau chắc tui sẽ đang", label: "BLUE" },
  { text: "Tui không hề nói... nha", label: "BLUE" },
  { text: "Thống kê chỉ ra rằng", label: "BLUE" },
  { text: "Tui có bảo... đâu", label: "BLUE" },
  { text: "Tui đâu có nói... đâu", label: "BLUE" },
  { text: "Ê, tui không nói gì không có nghĩa là tui không", label: "BLUE" },
  { text: "Giá như hồi đó tui", label: "BLUE" },
  { text: "Chắc/Hẳn là cậu nhầm... với... rồi", label: "BLUE" },
  { text: "Hơn ai hết cậu biết rõ... mà", label: "BLUE" },
  { text: "Chẳng có mấy người sẵn sàng... đâu", label: "BLUE" },
  { text: "Làm gì có cái gọi là", label: "BLUE" },
  { text: "Tui sẽ để nó cho cậu quyết định", label: "BLUE" },
  { text: "Tui biết nó nghe khá là khó tin nhưng mà", label: "BLUE" },
  { text: "Khi nói đến..., không ai là qua được", label: "BLUE" },
  { text: "Cậu không bao giờ phải lăn tăn/lo lắng về cái việc", label: "BLUE" },
  { text: "Ai đời lại", label: "BLUE" },
  { text: "Chẳng có lý gì", label: "BLUE" },
  { text: "Chẳng có lý do gì mà", label: "BLUE" },
  { text: "Ngoài đường người ta đồn rằng", label: "BLUE" },
  { text: "Người ta đồn rằng", label: "BLUE" },
  { text: "Cậu làm như ai cũng", label: "BLUE" },
  { text: "Cậu có biết tui đã phải trải qua những gì để có thể... không", label: "BLUE" },
  { text: "Ê đừng có lộn/nhầm giữa... với... nha", label: "BLUE" },
  { text: "Thực ra,... dễ hơn tui tưởng nhiều", label: "BLUE" },
  { text: "Càng... càng tốt", label: "BLUE" },
  { text: "Gần đây cậu có... không", label: "BLUE" },
  { text: "Để có được ngày hôm nay tui đã phải", label: "BLUE" },
  { text: "Tui ý thức rất rõ được rằng", label: "BLUE" },
  { text: "tui nhận thức rõ được rằng", label: "BLUE" },
  { text: "Điều gì làm cậu lo lắng... khi cậu", label: "BLUE" },
  { text: "Điều gì làm cậu thích khi", label: "BLUE" },
  { text: "Cậu thích điều gì khi", label: "BLUE" },
  { text: "Có một làn ranh rất mỏng giữa... và", label: "BLUE" },
  { text: "Tụi tui chơi với nhau ... năm rồi", label: "BLUE" },
  { text: "tụi tui biết nhau cũng ... năm rồi", label: "BLUE" },
  { text: "Tui có 3 năm kinh nghiệm làm", label: "BLUE" },
  { text: "Có ai mà chưa từng... đâu", label: "BLUE" },
  { text: "Cứ mỗi 5 năm tui lại phải... một lần", label: "BLUE" },
  { text: "Cậu phải chủ động", label: "BLUE" },
  { text: "Nghe chả giống... tí nào cả", label: "BLUE" },
  { text: "Tui sẽ chỉ cậu cách", label: "BLUE" },
  { text: "Tui đâu có... đến dzậy", label: "BLUE" },
  { text: "Thực ra, nó đâu có quá khó để nhận ra", label: "BLUE" },
  { text: "Tôi tin rằng hầu hết chúng ta", label: "BLUE" },
  { text: "... chứ nói gì đến", label: "BLUE" },
  { text: "Tui sẵn lòng giúp cậu nếu cậu", label: "BLUE" },
  { text: "Tôi thấy nó khá là", label: "BLUE" },
  { text: "Sẽ có rất nhiều", label: "BLUE" },
  { text: "Họ cứ nằng nặc đòi", label: "BLUE" },
  { text: "Tôi thách cậu dám... đấy", label: "BLUE" },
  { text: "Sâu bên trong tôi tin rằng", label: "BLUE" },
  { text: "Hôm qua tui tình cờ", label: "BLUE" },
  { text: "Đây là cái... nhất mà tui từng thấy trên đời đấy", label: "BLUE" },
  { text: "Chắc lúc đó tui đang", label: "BLUE" },
  { text: "Đừng có làm ra vẻ cậu không biết", label: "BLUE" },
  { text: "Tui rất biết ơn vì đã có cơ hội", label: "BLUE" },
  { text: "Không có nhiều người ngoài kia có thể", label: "BLUE" },
  { text: "Tôi nôn... quá", label: "BLUE" },
  { text: "Tui mong... quá", label: "BLUE" },
  { text: "Để chữa cháy, tui sẽ", label: "BLUE" },
  { text: "Tui thích cái cách", label: "BLUE" },
  { text: "... rất có ý nghĩa với tui", label: "BLUE" },
  { text: "Nó sẽ được giữ bí mật cho đến khi", label: "BLUE" },
  { text: "Cậu làm sao mà hiểu được", label: "BLUE" },
  { text: "Tui không thích... lắm", label: "BLUE" },
  { text: "Để tui xem cậu... đến cỡ nào", label: "BLUE" },
  { text: "Cậu không có... cậu không hiểu đâu", label: "BLUE" },
  { text: "Uả nãy giờ tui tưởng", label: "BLUE" },
  { text: "Tui từng rất là cùi bắp về", label: "BLUE" },
  { text: "Tui dị ứng với cái cách", label: "BLUE" },
  { text: "Uả, cậu là... hay gì", label: "BLUE" },
  { text: "(Nếu) biết vậy, tui đã... rồi", label: "BLUE" },
  { text: "Cái này sẽ ngăn không cho", label: "BLUE" },
  { text: "... sẽ là quá đủ cho dự án này", label: "BLUE" },
  { text: "... đang ngày càng", label: "BLUE" },
  { text: "Vấn đề là tui đã lỡ... rồi", label: "BLUE" },
  { text: "Cậu chỉ được cái... (là giỏi)", label: "BLUE" },
  { text: "Cứ cách ngày/tuần/tháng/năm, tui lại", label: "BLUE" },
  { text: "Cậu có hay", label: "BLUE" },
  { text: "Cậu có thường", label: "BLUE" },
  { text: "Sao cậu biết tui không", label: "BLUE" },
  { text: "Ê chính cậu nói tui là... nha", label: "BLUE" },
  { text: "Cho đến giờ tui vẫn", label: "BLUE" },
  { text: "Vấn đề mà tui sắp kể", label: "BLUE" },
  { text: "Tui chán ngấy cái cảnh", label: "BLUE" },
  { text: "Bậy giờ cậu có... hay là không", label: "BLUE" },
  { text: "Bây giờ tui đếm đến ba", label: "BLUE" },
  { text: "... đến cỡ nào", label: "BLUE" },
  { text: "Mỗi khi... tui lại", label: "BLUE" },
  { text: "... là một ví dụ điển hình cho cái này", label: "BLUE" },
  { text: "Sao cậu dám... một mình", label: "BLUE" },
  { text: "Hãy nhớ rằng", label: "BLUE" },
  { text: "Tui bị ấn tượng bởi cái cách", label: "BLUE" },
  { text: "Tin tốt là cậu sẽ không phải", label: "BLUE" },
  { text: "Tui rất thích..., trong khi đó", label: "BLUE" },
  { text: "Một mặt,... Mặt khác", label: "BLUE" },
  { text: "Tất cả chỉ là tại", label: "BLUE" },
  { text: "Miễn là", label: "BLUE" },
  { text: "Biết đâu tụi nó... (thì) sao", label: "BLUE" },
  { text: "Để tui tìm cách", label: "BLUE" },
  { text: "Tui luôn rất nể trọng", label: "BLUE" },
  { text: "Nói về cái này, không ai qua/thắng được", label: "BLUE" },
  { text: "Tui thà... chứ tui không bao giờ", label: "BLUE" },
  { text: "Chính cậu nhờ tui... nha", label: "BLUE" },
  { text: "Tui hứa tui sẽ không bao giờ", label: "BLUE" },
  { text: "Rất có thể", label: "BLUE" },
  { text: "Uả tui tưởng... chớ", label: "BLUE" },
  { text: "Nói vậy chẳng khác nào", label: "BLUE" },
  { text: "... suốt ấy mà", label: "BLUE" },
  { text: "... hoài ấy mà", label: "BLUE" },
  { text: "Đừng quên", label: "BLUE" },
  { text: "Nhớ rằng", label: "BLUE" },
  { text: "... Lâu chưa", label: "BLUE" },
  { text: "Tôi cá chắc", label: "BLUE" },
  { text: "Tôi dám chắc", label: "BLUE" },
  { text: "Không lẽ nào", label: "BLUE" },
  { text: "Làm gì có chuyện", label: "BLUE" },
  { text: "không đời nào", label: "BLUE" },
  { text: "Có khi nào", label: "BLUE" },
  { text: "có khả năng nào", label: "BLUE" },
  { text: "Tui không còn muốn... nữa", label: "BLUE" },
  { text: "... thì tui đi bằng đầu", label: "BLUE" },
  { text: "Tui có linh cảm rằng", label: "BLUE" },
  { text: "Trực giác mách bảo tui rằng", label: "BLUE" },
  { text: "Người ta hay bảo", label: "BLUE" },
  { text: "..., có thể nói vậy", label: "BLUE" },

  // RED (7 Ohm - Idioms & Nuance)
  { text: "Mật ngọt chết ruồi", label: "RED" },
  { text: "Có ai ở nhà không", label: "RED" },
  { text: "Thời gian trôi nhanh thật", label: "RED" },
  { text: "Có chuyện gì cậu muốn nói với tui không", label: "RED" },
  { text: "Tui không có sự lựa chọn", label: "RED" },
  { text: "Nó làm tui nổi hết cả da gà", label: "RED" },
  { text: "Nhớ đến đúng giờ nha", label: "RED" },
  { text: "Cậu tới số rồi", label: "RED" },
  { text: "Cho tui thêm 2 tuần đi", label: "RED" },
  { text: "Có gì (cứ) alo tui", label: "RED" },
  { text: "Đừng sợ!, có tui đây", label: "RED" },
  { text: "Cậu làm gì thì cậu tự biết", label: "RED" },
  { text: "Không tin thì cậu đi mà hỏi họ", label: "RED" },
  { text: "Đời là phù du", label: "RED" },
  { text: "Cậu xem tui là loại người gì", label: "RED" },
  { text: "Mai họ mới về lận", label: "RED" },
  { text: "Cậu có hiểu cậu đang nói cái gì không", label: "RED" },
  { text: "Dụ đó sao rồi", label: "RED" },
  { text: "Giữ liên lạc nha", label: "RED" },
  { text: "Cậu không ngồi yên được à", label: "RED" },
  { text: "Cái gì cũng có cái giá của nó", label: "RED" },
  { text: "Khoan chỗ đó cậu nói tui không hiểu", label: "RED" },
  { text: "Cậu giải thích tui lại được không", label: "RED" },
  { text: "Ê ê ê, cậu nói vậy là ý gì", label: "RED" },
  { text: "Ê, trông tui thế nào", label: "RED" },
  { text: "Cậu làm sao hay dzậy", label: "RED" },
  { text: "Cậu về phe nào", label: "RED" },
  { text: "Cậu bênh ai", label: "RED" },
  { text: "Thế thì hay quá", label: "RED" },
  { text: "Thế thì quá okay", label: "RED" },
  { text: "Tui biết ngay thế nào cậu cũng nói vậy mà", label: "RED" },
  { text: "Bả mà biết là bả cạo đầu tui luôn", label: "RED" },
  { text: "Cậu có biết tui là ai không", label: "RED" },
  { text: "Đổ thêm dầu vào lửa", label: "RED" },
  { text: "Mời cậu đi trước", label: "RED" },
  { text: "Nhớ mang theo nước", label: "RED" },
  { text: "Thêu dệt nên một câu chuyện", label: "RED" },
  { text: "Đừng có phạm cùng 1 sai lầm 2 lần", label: "RED" },
  { text: "Cậu ủng hộ hay chống đối cái này", label: "RED" },
  { text: "Ê câu đó của tui (nói) nha", label: "RED" },
  { text: "Đừng chờ nữa, họ không đến đâu", label: "RED" },
  { text: "Không biết mà lại là hay", label: "RED" },
  { text: "Không có gì là qua được mắt tui", label: "RED" },
  { text: "Đi chỗ khác chơi, nhìn gì mà nhìn", label: "RED" },
  { text: "Cậu có gì để mất", label: "RED" },
  { text: "(Cái đó) cũng dễ hiểu thôi", label: "RED" },
  { text: "Bút sa gà chết", label: "RED" },
  { text: "Tui có 1 câu hỏi", label: "RED" },
  { text: "Tui nói vậy có rõ chưa", label: "RED" },
  { text: "Tui nói vậy có dễ hiểu chưa", label: "RED" },
  { text: "Cậu nói sao ấy chớ", label: "RED" },
  { text: "Cậu nói thì dễ rồi", label: "RED" },
  { text: "Cám ơn/xin lỗi trước nha", label: "RED" },
  { text: "Cậu xong phim rồi", label: "RED" },
  { text: "cậu lên dĩa rồi", label: "RED" },
  { text: "Tui không có cố tình", label: "RED" },
  { text: "Tui đâu cố tình đâu", label: "RED" },
  { text: "Cậu có sao không", label: "RED" },
  { text: "cậu có bị thương không", label: "RED" },
  { text: "Ê đừng có nhìn tui vậy nha", label: "RED" },
  { text: "Vòng vo tam quốc", label: "RED" },
  { text: "Giờ tui nói cậu nghe nè", label: "RED" },
  { text: "Cậu điên à", label: "RED" },
  { text: "Cậu có điên không", label: "RED" },
  { text: "cậu có mất trí không", label: "RED" },
  { text: "Tui có cách rồi", label: "RED" },
  { text: "Mấy chuyện như này xảy ra hoài", label: "RED" },
  { text: "Chuyện bình thường", label: "RED" },
  { text: "Chờ đây, tui quay lại liền", label: "RED" },
  { text: "Giữ máy chút nha", label: "RED" },
  { text: "Tí nữa tui nói cho nghe", label: "RED" },
  { text: "Chuyện gì tới nó tới", label: "RED" },
  { text: "Tui không nghĩ đó là ý hay đâu", label: "RED" },
  { text: "Dễ như ăn bánh", label: "RED" },
  { text: "Tui không có lặp lại đâu nha", label: "RED" },
  { text: "tui không có nói lại đâu nha", label: "RED" },
  { text: "Vậy mà cậu cũng nói được", label: "RED" },
  { text: "Cậu đâu trong cảnh tui cậu đâu biết", label: "RED" },
  { text: "Tiền nào của đó thôi", label: "RED" },
  { text: "Tui nói gì sai à", label: "RED" },
  { text: "Đ đó không phải ý tui", label: "RED" },
  { text: "Ý tui không phải dzậy", label: "RED" },
  { text: "Khách hàng là thượng đế", label: "RED" },
  { text: "Cậu hiểu sao thì hiểu", label: "RED" },
  { text: "Nhìn mặt cậu là tui biết rồi", label: "RED" },
  { text: "Khi đời trở nên sóng gió", label: "RED" },
  { text: "khi mọi thứ không được thuận lợi", label: "RED" },
  { text: "Xa mặt cách lòng", label: "RED" },
  { text: "Cái gì cũng có lần đầu mà", label: "RED" },
  { text: "Rồi cậu sẽ làm gì", label: "RED" },
  { text: "Cậu tính sẽ làm gì", label: "RED" },
  { text: "Có gì tui báo", label: "RED" },
  { text: "Nó đâu có đơn giản vậy", label: "RED" },
  { text: "Cái quái gì đây", label: "RED" },
  { text: "Đó đâu phải chuyện của cậu", label: "RED" },
  { text: "Vài điều tốt hơn là không nên nói ra", label: "RED" },
  { text: "tốt hơn là nên giữ mồm giữ miệng", label: "RED" },
  { text: "Đừng có hối tui", label: "RED" },
  { text: "Cậu theo kịp không", label: "RED" },
  { text: "Ê dạo này sao rồi", label: "RED" },
  { text: "Rồi tui nên nói gì giờ", label: "RED" },
  { text: "Tiền không thành vấn đề", label: "RED" },
  { text: "Tui muốn nói tiếp chỗ mình dừng hôm bữa nha", label: "RED" },
  { text: "Nó liên quan gì đến chuyện mà ta đang nói", label: "RED" },
  { text: "Nhìn cho kỹ dzô", label: "RED" },
  { text: "Uả xí, tui chưa hiểu gì hết", label: "RED" },
  { text: "Im lặng", label: "RED" },
  { text: "im hết coi", label: "RED" },
  { text: "Sao mặt buồn so dzậy", label: "RED" },
  { text: "Sao mặt đưa đám dzậy", label: "RED" },
  { text: "Xin lỗi làm phiền anh giờ này nha", label: "RED" },
  { text: "Àaa, ra là dzậy", label: "RED" },
  { text: "Thôi đừng có càm ràm nữa", label: "RED" },
  { text: "Nếu cậu không phiền tui hỏi", label: "RED" },
  { text: "nếu cậu không phiền", label: "RED" },
  { text: "Tui nhờ cậu (1) chuyện được không", label: "RED" },
  { text: "Cậu (đang) nói cái gì dzậy", label: "RED" },
  { text: "Lẹ lên, tui không có rảnh à", label: "RED" },
  { text: "Cậu theo kịp tui không", label: "RED" },
  { text: "Tui có nói nhanh quá không", label: "RED" },
  { text: "Cách đó không có work", label: "RED" },
  { text: "cách đó không được đâu", label: "RED" },
  { text: "Cậu thử chưa mà biết", label: "RED" },
  { text: "Sao cậu biết không được", label: "RED" },
  { text: "Tui biết ngay thế nào cậu cũng nói dzậy mà", label: "RED" },
  { text: "Cậu không biết cái đó hả", label: "RED" },
  { text: "Một phần không thể thiếu của cuộc sống", label: "RED" },
  { text: "Chuyện gì rồi cũng có cách giải quyết thôi", label: "RED" },
  { text: "Nói được làm được nha", label: "RED" },
  { text: "Tui có tin tốt/xấu cho cậu đây", label: "RED" },
  { text: "Tui nhờ cậu này được không", label: "RED" },
  { text: "Cậu giúp tui chuyện được không", label: "RED" },
  { text: "Đẹp quá ta", label: "RED" },
  { text: "9 người 10 ý", label: "RED" },
  { text: "Làm sao (mà) tui biết được", label: "RED" },
  { text: "Cậu có cần tui giúp một tay không", label: "RED" },
  { text: "Tui nợ cậu lần này", label: "RED" },
  { text: "Bình tĩnh", label: "RED" },
  { text: "hết sức bình tĩnh", label: "RED" },
  { text: "bình tĩnh, có phải tận thế đâu", label: "RED" },
  { text: "Đâm sau lưng", label: "RED" },
  { text: "Nó làm tui mất ngủ nhiều đêm", label: "RED" },
  { text: "Tóm lại cậu muốn cái gì ở tui", label: "RED" },
  { text: "Tóm lại thì tui làm được cái gì", label: "RED" },
  { text: "Tui nói nãy giờ cậu không hiểu hả", label: "RED" },
  { text: "Được ăn cả ngã về không", label: "RED" },
  { text: "Nói lớn lên tui chả nghe gì cả", label: "RED" },
  { text: "Chính xác", label: "RED" },
  { text: "Chuẩn", label: "RED" },
  { text: "Đừng có chĩa mũi vào chuyện người khác", label: "RED" },
  { text: "Cái này đâu phải chuyện của cậu", label: "RED" },
  { text: "Cậu join không", label: "RED" },
  { text: "cậu tham gia không", label: "RED" },
  { text: "Đó chỉ là vấn đề thời gian thôi", label: "RED" },
  { text: "Cậu thích cái nào hơn", label: "RED" },
  { text: "Cậu thì biết cái gì mà nói", label: "RED" },
  { text: "Quá ảo", label: "RED" },
  { text: "Ảo ma canada", label: "RED" },
  { text: "Ảo thế", label: "RED" },
  { text: "Khó tin thế", label: "RED" },
  { text: "Tui nghĩ thông (suốt) rồi", label: "RED" },
  { text: "Cậu vừa nói gì", label: "RED" },
  { text: "Cái đó nghe quen lắm nha", label: "RED" },
  { text: "Thực hiện 1 giao dịch", label: "RED" },
  { text: "Tui không có bị dụ đâu", label: "RED" },
  { text: "Chúc bạn may mắn lần sau", label: "RED" },
  { text: "Cậu nghe đúng rồi đấy", label: "RED" },
  { text: "Nó hiệu quả như thuốc tiên ấy", label: "RED" },
  { text: "Nó rất là hiệu quả nha", label: "RED" },
  { text: "Rõ ràng anh có nói/làm vậy nha", label: "RED" },
  { text: "Tui không biết ảnh/cổ có nói cậu chưa", label: "RED" },
  { text: "Làm vậy mất nhiều thời gian lắm", label: "RED" },
  { text: "Giờ cậu có rảnh nói chuyện chút không", label: "RED" },
  { text: "Tui nói chuyện cậu chút được không", label: "RED" },
  { text: "Đừng có kén chọn quá", label: "RED" },
  { text: "Bữa tiệc nào rồi cũng có lúc tàn", label: "RED" },
  { text: "Tui bị lây thói quen của cậu đấy", label: "RED" },
  { text: "Lúc nào tui cũng phải nhìn ngó nơm nớp lo sợ", label: "RED" },
  { text: "Đừng có mà tưởng bở", label: "RED" },
  { text: "Nhìn vậy không phải vậy đâu", label: "RED" },
  { text: "Có gì là khác nhau", label: "RED" },
  { text: "Khác nhau chỗ nào", label: "RED" },
  { text: "Ê tui thì liên quan gì", label: "RED" },
  { text: "Có cái gì đó không hợp lý lắm ở đây", label: "RED" },
  { text: "Đừng có giả điên với tui", label: "RED" },
  { text: "Đừng có chơi trò mèo vờn chuột với tui", label: "RED" },
  { text: "Cậu đi guốc trong bụng tui rồi", label: "RED" },
  { text: "Không có đơn giản vậy đâu", label: "RED" },
  { text: "Có gì tui báo cậu sau", label: "RED" },
  { text: "Tưởng gì mà tưởng", label: "RED" },
  { text: "Cậu đến/tới được không", label: "RED" },
  { text: "Chúc cậu một ngày/buổi tối vui vẻ", label: "RED" },
  { text: "Đó là tất cả những gì tui quan tâm", label: "RED" },
  { text: "Cay thiệt chớ", label: "RED" },
  { text: "Đừng có để bụng nha", label: "RED" },
  { text: "Alo?!? cậu bị làm sao dzậy", label: "RED" },
  { text: "Đứng im", label: "RED" },
  { text: "Mọi thứ đều có lý do của nó cả", label: "RED" },
  { text: "Không có gì là tự nhiên hết", label: "RED" },
  { text: "Mấy lúc đó cậu biết tui hay làm gì không", label: "RED" },
  { text: "Quề dốn thiệt", label: "RED" },
  { text: "Kệ (nó) đi", label: "RED" },
  { text: "Nhìn vậy mà không phải vậy", label: "RED" },
  { text: "Không thể tin được", label: "RED" },
  { text: "Ai bao", label: "RED" },
  { text: "Đứa nào bao", label: "RED" },
  { text: "Đứa nào khao", label: "RED" },
  { text: "Tính tui vô nữa", label: "RED" },
  { text: "Cho tui 1 vé", label: "RED" },
  { text: "Bữa tối nay tui mời", label: "RED" },
  { text: "Buông ra", label: "RED" },
  { text: "buông tui ra", label: "RED" },
  { text: "Nhấp môi cái thôi", label: "RED" },
  { text: "Làm ngụm đi", label: "RED" },
  { text: "Sao, dụ gì", label: "RED" },
  { text: "Cậu làm sao coi cho được đó nha", label: "RED" },
  { text: "Sao lại (là) tại tui", label: "RED" },
  { text: "Sao lúc nào cũng là tui", label: "RED" },
  { text: "Nói nhớ giữ lời nha", label: "RED" },
  { text: "Ở đây cái đó là cấm kị đấy", label: "RED" },
  { text: "Cậu đang dọa tui đấy à", label: "RED" },
  { text: "Gieo gió thì gặt bão thôi", label: "RED" },
  { text: "Luật hoa quả thôi", label: "RED" },
  { text: "Tụi nó sẽ cho cậu biết tay", label: "RED" },
  { text: "Coi chừng chó dữ", label: "RED" },
  { text: "Cậu đi đâu dzậy", label: "RED" },
  { text: "Họ tới liền giờ ấy", label: "RED" },
  { text: "Rồi cậu sẽ hiểu", label: "RED" },
  { text: "Hẳn là tui gặp cậu ở đâu rồi", label: "RED" },
  { text: "Chắc họ đang (trên đường) qua đấy", label: "RED" },
  { text: "Đừng bao giờ xem thường bất kỳ ai", label: "RED" },
  { text: "Cậu nói cũng phải", label: "RED" },
  { text: "Cậu có lý đấy", label: "RED" },
  { text: "Đừng có để người ta đợi", label: "RED" },
  { text: "Thời gian sẽ trả lời", label: "RED" },
  { text: "Vậy là cậu tự đào hố chôn mình rồi", label: "RED" },
  { text: "Làm vậy tình hình sẽ chỉ tệ hơn", label: "RED" },
  { text: "Yêu từ cái nhìn đầu tiên", label: "RED" },
  { text: "Lụm tui ly cà phê", label: "RED" },
  { text: "Lúc đó cậu biết tui nghĩ gì không", label: "RED" },
  { text: "Cậu sẽ sớm quen với cái đó thôi", label: "RED" },
  { text: "Cất cái đó đi", label: "RED" },
  { text: "Đứng núi này trông núi nọ", label: "RED" },
  { text: "Cậu được cảnh báo trước rồi đó nha", label: "RED" },
  { text: "Im lặng là đồng ý", label: "RED" },
  { text: "Chân tui đau quá", label: "RED" },
  { text: "Cậu có dầu gió không", label: "RED" },
  { text: "Cậu có gì muốn nói với tôi không", label: "RED" },
  { text: "Đó quả là một hiện tượng", label: "RED" },
  { text: "Đáp ứng nhu cầu thị trường", label: "RED" },
  { text: "Bắt đầu lại từ đầu", label: "RED" },
  { text: "Để mai tính", label: "RED" },
  { text: "Không có gì là dễ dàng cả", label: "RED" },
  { text: "Nhớ để mắt tới cái đó", label: "RED" },
  { text: "Thông cảm tui cái đi mà", label: "RED" },
  { text: "Cậu phải nghe tui lần này", label: "RED" },
  { text: "Bó tay", label: "RED" },
  { text: "Cậu làm gì (ở) trỏng lâu dzậy", label: "RED" },
  { text: "Sao giờ cậu mới tới", label: "RED" },
  { text: "Cậu biết tui chờ bao lâu rồi không", label: "RED" },
  { text: "Trôi theo dòng", label: "RED" },
  { text: "Cậu đùa tui à", label: "RED" },
  { text: "Tui nói (cái) gì sai à", label: "RED" },
  { text: "Cậu thì biết gì mà nói", label: "RED" },
  { text: "Tạo ra tác động tích cực", label: "RED" },
  { text: "Cái này là chuyện giữa tui với cậu", label: "RED" },
  { text: "Đó chỉ là công cụ đạt đến mục đích cuối thôi", label: "RED" },
  { text: "Cái đó tui bị rồi", label: "RED" },
  { text: "Cái đó xảy ra với tui rồi", label: "RED" },
  { text: "Không thể xảy ra một sớm một chiều", label: "RED" },
  { text: "Bắt đầu từ số 0", label: "RED" },
  { text: "Chúc ngon miệng (nha)", label: "RED" },
  { text: "Thế giới thiệt là tròn", label: "RED" },
  { text: "Bất ngờ quá dzậy", label: "RED" },
  { text: "Đừng có mà coi thường người khác nha", label: "RED" },
  { text: "Càng đông càng vui", label: "RED" },
  { text: "Chắc để khi khác đi", label: "RED" },
  { text: "Rõ như ban ngày", label: "RED" },
  { text: "Nói trước bước không qua", label: "RED" },
  { text: "Sếp mà biết chắc ổng cạo đầu tui luôn quá", label: "RED" },
  { text: "Làm gì còn cách nào khác", label: "RED" },
  { text: "Cậu làm vậy mà coi được à", label: "RED" },
  { text: "Để coi lần này ai sẽ cứu cậu", label: "RED" },
  { text: "Chưa đến lúc đâu", label: "RED" },
  { text: "Thời cơ chưa chín mùi", label: "RED" },
  { text: "Cậu còn chờ cái gì nữa", label: "RED" },
  { text: "Sao cậu làm được hay dzậy", label: "RED" },
  { text: "Đừng có đùa với lửa", label: "RED" },
  { text: "Rồi cậu sẽ sớm quen thôi", label: "RED" },
  { text: "Rồi ai sẽ chống lưng cho cậu", label: "RED" },
  { text: "Tui thấy hết rồi, cậu đừng có chối nữa", label: "RED" },
  { text: "Xin lỗi ghế này có ai ngồi chưa", label: "RED" },
  { text: "Chắc cậu nghe nhầm rồi", label: "RED" },
  { text: "Trời, cậu bày vẽ quá làm gì", label: "RED" },
  { text: "Cậu đang giả bộ không hiểu đó hả", label: "RED" },
  { text: "Cái đó không đúng với tui", label: "RED" },
  { text: "cái đó không áp dụng với tui nha", label: "RED" },
  { text: "Ủa, hai người biết nhau trước rồi à", label: "RED" },
  { text: "Giờ tui phải làm sao đây", label: "RED" },
  { text: "Tui chẳng có gì phải hối hận cả", label: "RED" },
  { text: "Cậu có đồng hồ đó không", label: "RED" },
  { text: "Cũng khuya rồi tui về đây", label: "RED" },
  { text: "Cậu nghĩ vậy à", label: "RED" },
  { text: "Cũng khó nói/đoán lắm", label: "RED" },
  { text: "Không phải gu của tui", label: "RED" },
  { text: "Không đơn giản thế đâu", label: "RED" },
  { text: "Bữa nào cafe", label: "RED" },
  { text: "Có dịp tui kể cậu nghe sau", label: "RED" },
  { text: "Cậu có đang hẹn hò với ai không", label: "RED" },
  { text: "Tui cũng vậy", label: "RED" },
  { text: "Giờ cậu biết làm rồi đấy", label: "RED" },
  { text: "Khoan cám ơn tui vội", label: "RED" },
  { text: "Còn miếng cafe nào cho tui không", label: "RED" },
  { text: "Đừng có nói thế", label: "RED" },
  { text: "Làm theo tui", label: "RED" },
  { text: "(Đi) theo tui", label: "RED" },
  { text: "Sao cậu nói như dzậy được", label: "RED" },
  { text: "Họ làm gì cậu", label: "RED" },
  { text: "Tui chẳng có ý gì cả", label: "RED" },
  { text: "Để dụ đó tui lo", label: "RED" },
  { text: "Cậu còn giận tui à", label: "RED" },
  { text: "Anh vừa nói gì cơ", label: "RED" },
  { text: "Vỏ quýt dày có móng tay nhọn", label: "RED" },
  { text: "Bây giờ anh lo cái gì", label: "RED" },
  { text: "Làm sao tui biết được", label: "RED" },
  { text: "Họ có nói gì tui đâu", label: "RED" },
  { text: "Cái này không phải ưu tiên hàng đầu của tui", label: "RED" },
  { text: "Cậu đang nghĩ gì đấy", label: "RED" },
  { text: "Đồ ăn ngụi hết rồi", label: "RED" },
  { text: "Vậy thì đã sao", label: "RED" },
  { text: "Tui đang đi nghỉ mát", label: "RED" },
  { text: "Hi vọng cậu đã có một cuối tuần vui vẻ", label: "RED" },
  { text: "Tùy cậu", label: "RED" },
  { text: "Bóp chết từ trong trứng nước", label: "RED" },
  { text: "Tui cũng không tin vào mắt mình", label: "RED" },
  { text: "... (x2) cái đầu cậu", label: "RED" },
  { text: "Tui chẳng còn sự lựa chọn nào khác cả", label: "RED" },
  { text: "Tui đã đi quá xa không còn đường quay lại nữa", label: "RED" },
  { text: "Cái đó thì tui đồng ý với cậu", label: "RED" },

  // PINK (9 Ohm - Key Terms)
  { text: "Dép lào", label: "PINK" },
  { text: "Tham lam", label: "PINK" },
  { text: "Qúa rõ ràng", label: "PINK" },
  { text: "Khui bia", label: "PINK" },
  { text: "Dùng một lần", label: "PINK" },
  { text: "Tẩy não", label: "PINK" },
  { text: "Trì hoãn dự án", label: "PINK" },
  { text: "Kêu gọi tẩy chay", label: "PINK" },
  { text: "Mất bình tĩnh", label: "PINK" },
  { text: "Cố tình", label: "PINK" },
  { text: "Mưa lớn", label: "PINK" },
  { text: "Còn sống", label: "PINK" },
  { text: "Ói", label: "PINK" },
  { text: "Mãn tính", label: "PINK" },
  { text: "Bà bầu", label: "PINK" },
  { text: "Xếp hàng", label: "PINK" },
  { text: "Lên cân", label: "PINK" },
  { text: "Không thể tránh khỏi", label: "PINK" },
  { text: "Bỏ việc", label: "PINK" },
  { text: "Cố chấp", label: "PINK" },
  { text: "Lời dèm pha", label: "PINK" },
  { text: "Tắt đèn", label: "PINK" },
  { text: "Khống số liệu", label: "PINK" },
  { text: "Ví điện tử", label: "PINK" },
  { text: "Đi tu", label: "PINK" },
  { text: "Đi tù", label: "PINK" },
  { text: "2/3", label: "PINK" },
  { text: "Dao động", label: "PINK" },
  { text: "Đặt chân đến", label: "PINK" },
  { text: "Hết pin", label: "PINK" },
  { text: "Thuế thu nhập cá nhân", label: "PINK" },
  { text: "Tôn Ngộ Không", label: "PINK" },
  { text: "Món quà tinh thần", label: "PINK" },
  { text: "Bệnh viên công", label: "PINK" },
  { text: "Nước mắm", label: "PINK" },
  { text: "Về quê", label: "PINK" },
  { text: "Nhẫn nhịn", label: "PINK" },
  { text: "Sang chấn", label: "PINK" },
  { text: "Cứng họng", label: "PINK" },
  { text: "Bỏ tay vào túi", label: "PINK" },
  { text: "Chống nạnh", label: "PINK" },
  { text: "Tằng hắng", label: "PINK" },
  { text: "Có tâm", label: "PINK" },
  { text: "Đổ sông đổ biển", label: "PINK" },
  { text: "Ẫn dụ", label: "PINK" },
  { text: "Khó chịu/khó chiều", label: "PINK" },
  { text: "Vô tri", label: "PINK" },
  { text: "Hống hách", label: "PINK" },
  { text: "Thất thường", label: "PINK" },
  { text: "Chảnh", label: "PINK" },
  { text: "tránh xa khỏi", label: "PINK" },
  { text: "Về lâu về dài", label: "PINK" },
  { text: "Muối tôm", label: "PINK" },
  { text: "Để ý tới", label: "PINK" },
  { text: "chú ý tới", label: "PINK" },
  { text: "để tâm đến", label: "PINK" },
  { text: "Đễ mắt tới", label: "PINK" },
  { text: "Tận dụng", label: "PINK" },
  { text: "lợi dụng", label: "PINK" },
  { text: "Cái gọi là", label: "PINK" },
  { text: "Xem nhẹ", label: "PINK" },
  { text: "Nhận ra", label: "PINK" },
  { text: "Phát hiện ra", label: "PINK" },
  { text: "... rất/quá là tào lao", label: "PINK" },
  { text: "... quá là dở/tệ", label: "PINK" },
  { text: "Hợp rơ", label: "PINK" },
  { text: "hợp cạ", label: "PINK" },
  { text: "Nghĩ ra", label: "PINK" },
  { text: "tìm ra", label: "PINK" },
  { text: "Bánh vẽ", label: "PINK" },
  { text: "Lật đật", label: "PINK" },
  { text: "vội vã", label: "PINK" },
  { text: "Vấn đề trước mắt", label: "PINK" },
  { text: "Vấn đề sống còn", label: "PINK" },
  { text: "Nãy giờ", label: "PINK" },
  { text: "Vô hiệu hóa", label: "PINK" },
  { text: "Đụng phải cùng một vấn đề", label: "PINK" },
  { text: "Đối phó với", label: "PINK" },
  { text: "Nhìn đều", label: "PINK" },
  { text: "Nhìn nhìn ngó ngó", label: "PINK" },
  { text: "Bắt tai", label: "PINK" },
  { text: "Hết giờ", label: "PINK" },
  { text: "Một đứa bạn của tui", label: "PINK" },
  { text: "tỉ lệ thuận", label: "PINK" },
  { text: "Trải/đi/kinh qua vô vàn những khó khăn", label: "PINK" },
  { text: "Truyền miệng", label: "PINK" },
  { text: "Quán ruột", label: "PINK" },
  { text: "Khách vãng lai", label: "PINK" },
  { text: "Rút kinh nghiệm", label: "PINK" },
  { text: "Trễ họp", label: "PINK" },
  { text: "Sến", label: "PINK" },
  { text: "sến súa", label: "PINK" },
  { text: "giả ngơ", label: "PINK" },
  { text: "giả điếc", label: "PINK" },
  { text: "bị khép góc", label: "PINK" },
  { text: "Okay chốt", label: "PINK" },
  { text: "Soán ngôi", label: "PINK" },
  { text: "So với cùng kỳ năm ngoái", label: "PINK" },
  { text: "Không có cửa thắng", label: "PINK" },
  { text: "Tạo thêm giá trị", label: "PINK" },
  { text: "Cắt giảm chi phí", label: "PINK" },
  { text: "Sẽ có thể", label: "PINK" },
  { text: "Lưu loát và mạch lạc", label: "PINK" },
  { text: "Đánh giá cao", label: "PINK" },
  { text: "Một điểm cộng lớn", label: "PINK" },
  { text: "Làm tui bực", label: "PINK" },
  { text: "chọc điên tui", label: "PINK" },
  { text: "Cú đêm", label: "PINK" },
  { text: "Công an phường", label: "PINK" },
  { text: "Hải quan", label: "PINK" },
  { text: "Chú Cuội", label: "PINK" },
  { text: "Gà ta", label: "PINK" },
  { text: "Bánh trung thu", label: "PINK" },
  { text: "Áy náy", label: "PINK" },
  { text: "ở ẩn", label: "PINK" },
  { text: "Chạy một dự án", label: "PINK" },
  { text: "Chậm nhất là chủ nhật", label: "PINK" },
  { text: "Ngon bổ rẻ", label: "PINK" },
  { text: "Tiêu chảy", label: "PINK" },
  { text: "Ngất xỉu", label: "PINK" },
  { text: "Trong gang tấc", label: "PINK" },
  { text: "Cầu vồng", label: "PINK" },
  { text: "Nửa vời", label: "PINK" },
  { text: "Yêu quái", label: "PINK" },
  { text: "Ưu tiên hàng đầu", label: "PINK" },
  { text: "Diễn đạt suy nghĩ", label: "PINK" },
  { text: "Tửu lượng", label: "PINK" },
  { text: "3 ngày liền", label: "PINK" },
  { text: "Vỉa hè", label: "PINK" },
  { text: "1 2 3 Dzô", label: "PINK" },
  { text: "Cưa bill (chia bill)", label: "PINK" },
  { text: "Ghế nóng", label: "PINK" },
  { text: "cờ tỉ phú", label: "PINK" },
  { text: "giữ bí mật", label: "PINK" },
  { text: "Ngon banh xác", label: "PINK" },
  { text: "Qúa đáng", label: "PINK" },
  { text: "Luật bất thành văn", label: "PINK" },
  { text: "Đỉnh của đỉnh", label: "PINK" },
  { text: "Thiên vị", label: "PINK" },
  { text: "Nước mía", label: "PINK" },
  { text: "Cùng một lúc", label: "PINK" },
  { text: "Thức khuya dậy sớm", label: "PINK" },
  { text: "Vòng tròn luẩn quẩn", label: "PINK" },
  { text: "Heo đất", label: "PINK" },
  { text: "Chu đáo", label: "PINK" },
  { text: "Phản tác dụng", label: "PINK" },
  { text: "Thăng trầm", label: "PINK" },
  { text: "Thao túng", label: "PINK" },
  { text: "Đầu cơ", label: "PINK" },
  { text: "Trưởng thành", label: "PINK" },
  { text: "Hồi phục", label: "PINK" },
  { text: "Thức ăn đường phố", label: "PINK" },
  { text: "Sự thật trần trụi", label: "PINK" },
  { text: "Cháo hành", label: "PINK" },
  { text: "Làm động tác giả", label: "PINK" },
  { text: "Sư tử cái", label: "PINK" },
  { text: "Tưới cây", label: "PINK" },
  { text: "Đi rón rén", label: "PINK" },
  { text: "Sống thử", label: "PINK" },
  { text: "Cách mạng hóa", label: "PINK" },
  { text: "Nhà thương điên", label: "PINK" },
  { text: "Xin chữ ký", label: "PINK" },
  { text: "Ngày trọng đại", label: "PINK" },
  { text: "100% nha", label: "PINK" },
  { text: "Uống hết nha", label: "PINK" },
  { text: "Cạn chén", label: "PINK" },
  { text: "Bắt taxi", label: "PINK" },
  { text: "Vượt đèn đỏ", label: "PINK" },
  { text: "Giật dây", label: "PINK" },
  { text: "Đồng bằng sông Cửu Long", label: "PINK" },
  { text: "Không hạt", label: "PINK" },
  { text: "Những người có liên quan", label: "PINK" },
  { text: "Làm việc nhà", label: "PINK" },
  { text: "Thuật ngữ", label: "PINK" },
  { text: "Tiếng Anh bồi", label: "PINK" },
  { text: "Cận thị", label: "PINK" },
  { text: "Nhảy việc", label: "PINK" },
  { text: "Chuỗi cung ứng", label: "PINK" },
  { text: "Vấn đề thiếu người", label: "PINK" },
  { text: "Đi đường vòng", label: "PINK" },
  { text: "Tập gym", label: "PINK" },
  { text: "Trực giác", label: "PINK" },
  { text: "Thái độ mỉa mai", label: "PINK" },
  { text: "Trên trời", label: "PINK" },
  { text: "Thời buổi này", label: "PINK" },
  { text: "COCC", label: "PINK" },
  { text: "Xe lăn", label: "PINK" },
  { text: "Đường tắt", label: "PINK" },
  { text: "Hột quẹt", label: "PINK" },
  { text: "Lửa trại", label: "PINK" },
  { text: "Tương xí muội", label: "PINK" },
  { text: "Cái mẹo", label: "PINK" },
  { text: "Áo phao", label: "PINK" },
  { text: "Chiếu tướng", label: "PINK" },
  { text: "Món tráng miệng", label: "PINK" },
  { text: "Hào phóng", label: "PINK" },
  { text: "Khiêm tốn", label: "PINK" },
  { text: "Trụ cột gia đình", label: "PINK" },
  { text: "Keo kiệt", label: "PINK" },
  { text: "Bánh tráng trộn", label: "PINK" },
  { text: "Tiểu đường", label: "PINK" },
  { text: "Hoành thánh", label: "PINK" },
  { text: "Di chúc", label: "PINK" },
  { text: "Có hiệu lực", label: "PINK" },
  { text: "Thâm nhập thị trường", label: "PINK" },
  { text: "Thị trường ngách", label: "PINK" },
  { text: "Cây xăng", label: "PINK" },
  { text: "Phá sản", label: "PINK" },
  { text: "Giá cả cạnh tranh", label: "PINK" },
  { text: "Nước ngọt", label: "PINK" },
  { text: "Thập kỷ", label: "PINK" },
  { text: "Đóng vai nạn nhân", label: "PINK" },
  { text: "Xoài Non", label: "PINK" },
  { text: "Khoai tây chiên", label: "PINK" },
  { text: "Nhiều dầu mỡ", label: "PINK" },
  { text: "Hợp vệ sinh", label: "PINK" },
  { text: "Gánh nặng tài chính", label: "PINK" },
  { text: "Tuần trăng mật", label: "PINK" },
  { text: "Liên tục", label: "PINK" },
  { text: "Diễn viên hạng A", label: "PINK" },
  { text: "Người vô gia cư", label: "PINK" },
  { text: "Đám tang", label: "PINK" },
  { text: "Sa thải", label: "PINK" },
  { text: "Múa lân", label: "PINK" },
  { text: "Tình yêu vô điều kiện", label: "PINK" },
  { text: "Cái giếng", label: "PINK" },
  { text: "Thả diều", label: "PINK" },
  { text: "Trái bơ", label: "PINK" },
  { text: "Sinh tố", label: "PINK" },
  { text: "Sữa đặc", label: "PINK" },
  { text: "Bột ngọt", label: "PINK" },
  { text: "Ô nhiễm", label: "PINK" },
  { text: "Bắt nạt", label: "PINK" },
  { text: "Vi phạm", label: "PINK" },
  { text: "Gót chân Asin' (Điểm chí mạng)", label: "PINK" },
  { text: "Uống thuốc", label: "PINK" },
  { text: "Ăn cắp vặt", label: "PINK" },
  { text: "Phá đám", label: "PINK" },
  { text: "Thuận tay trái", label: "PINK" },
  { text: "Tạo không khí tích cực", label: "PINK" },
  { text: "Đền tội", label: "PINK" },
  { text: "Con người chúng ta", label: "PINK" },
  { text: "Con người mình", label: "PINK" },
  { text: "Bà tám", label: "PINK" },
  { text: "nhiều chuyện", label: "PINK" },
  { text: "Nền kinh tế lớn thứ hai", label: "PINK" },
  { text: "Dọn vô", label: "PINK" },
  { text: "Sự cố ngoài ý muốn", label: "PINK" },
  { text: "Ba phải", label: "PINK" },
  { text: "Chiếm 10%", label: "PINK" },
  { text: "Tầm nhìn hạn hẹp", label: "PINK" },
  { text: "Đứng lên bên vực cho", label: "PINK" },
  { text: "Đi nhậu", label: "PINK" },
  { text: "Ba vợ", label: "PINK" },
  { text: "Chính trực", label: "PINK" },
  { text: "Kẹt xe", label: "PINK" },
  { text: "Cối xay gió", label: "PINK" },
  { text: "Ở trên lầu", label: "PINK" },
  { text: "Một tên tuổi lớn", label: "PINK" },
  { text: "Sâu bên trong", label: "PINK" },
  { text: "Đầu tư vào", label: "PINK" },
  { text: "Nhúng chàm", label: "PINK" },
  { text: "Xe bán tải", label: "PINK" },
  { text: "Khẩn cấp", label: "PINK" },
  { text: "Ăn khuya", label: "PINK" },
  { text: "Giữ lịch sự", label: "PINK" },
  { text: "Khủng hoảng", label: "PINK" },
  { text: "Bình dân", label: "PINK" },
  { text: "Bảo hiểm y tế", label: "PINK" },
  { text: "Tống tiền", label: "PINK" },
  { text: "Bắt cóc", label: "PINK" },
  { text: "Có lời", label: "PINK" },
  { text: "Truyền lửa", label: "PINK" },
  { text: "Người đi đường", label: "PINK" },
  { text: "Dân địa phương", label: "PINK" },
  { text: "Cân bằng", label: "PINK" },
  { text: "Đăng nhập", label: "PINK" },
  { text: "Biểu tượng", label: "PINK" },
  { text: "Tiền lẻ", label: "PINK" },
  { text: "Câu cửa miệng", label: "PINK" },
  { text: "Coi chừng", label: "PINK" },
  { text: "Ngứa ngáy", label: "PINK" },
  { text: "Ngáp", label: "PINK" },
  { text: "Trượt mục tiêu", label: "PINK" },
  { text: "Rượu mạnh", label: "PINK" },
  { text: "Cafe gói", label: "PINK" },
  { text: "Chị Hằng", label: "PINK" },
  { text: "Trăng tròn", label: "PINK" },
  { text: "Lý do lý trấu", label: "PINK" },
  { text: "Chuyện cổ tích", label: "PINK" },
  { text: "Cơm tấm", label: "PINK" },
  { text: "Ông k kẹ", label: "PINK" },
  { text: "Điều hành", label: "PINK" },
  { text: "Hệ điều hành", label: "PINK" },
  { text: "Lỗi đánh máy", label: "PINK" },
  { text: "Bỏ áo vào quần' (đóng thùng)", label: "PINK" },
  { text: "Mắm tôm", label: "PINK" },
  { text: "Mặt nạ", label: "PINK" },
  { text: "Cà vạt", label: "PINK" },
  { text: "Vớ", label: "PINK" },
  { text: "Cải thiện", label: "PINK" },
  { text: "Cái thớt", label: "PINK" },
  { text: "Máy lạnh", label: "PINK" },
  { text: "Thang máy", label: "PINK" },
  { text: "Xanh đậm", label: "PINK" }
];
