import { OhmLabel } from './types.ts';

export interface DatabaseEntry {
  text: string;
  label: OhmLabel;
}

// Trích xuất từ BOOK OF NUANCE WORDS để làm Memory Resource
export const KNOWN_PHRASES: DatabaseEntry[] = [
  // GREEN (Gap Fillers)
  { text: "Từ bây giờ", label: "GREEN" },
  { text: "Từ giờ trở đi", label: "GREEN" },
  { text: "Tui không phiền kể cậu cái này", label: "GREEN" },
  { text: "Cả ngày hôm qua", label: "GREEN" },
  { text: "Sao phải vội thế", label: "GREEN" },
  { text: "Cậu vội cái gì", label: "GREEN" },
  { text: "Theo lẽ thường", label: "GREEN" },
  { text: "Logic mà nói", label: "GREEN" },
  { text: "Chịu!", label: "GREEN" },
  { text: "Tui thua rồi đấy", label: "GREEN" },
  { text: "Đề đền bù cho cậu", label: "GREEN" },
  { text: "Tui không biết ai cho/tiêm cái đó vào đầu cậu", label: "GREEN" },
  { text: "Cám ơn vì đã mời tui", label: "GREEN" },
  { text: "Đừng có ngại", label: "GREEN" },
  { text: "Đừng có khách sáo", label: "GREEN" },
  { text: "Chẳng sớm thì muộn", label: "GREEN" },
  { text: "Để rồi, cho đến một ngày", label: "GREEN" },
  { text: "Trên đường tới đây", label: "GREEN" },
  { text: "Tin tui đi", label: "GREEN" },
  { text: "Nếu tui mà là cậu", label: "GREEN" },
  { text: "Nếu cậu mà là tui", label: "GREEN" },
  { text: "Nếu đó là sự thật", label: "GREEN" },
  { text: "Tui đâu phải con nít", label: "GREEN" },
  { text: "Nghĩ xem", label: "GREEN" },
  { text: "Dễ hiểu thôi", label: "GREEN" },
  { text: "Nói chung", label: "GREEN" },
  { text: "Thẳng thắn mà nói", label: "GREEN" },

  // BLUE (Sentence Frames)
  { text: "Cậu nên nhớ rằng", label: "BLUE" },
  { text: "Nếu cậu mà biết nghĩ thì cậu đâu có", label: "BLUE" },
  { text: "Tui thực sự không có đủ thời gian để", label: "BLUE" },
  { text: "Tui không hiểu cậu lấy đâu ra nhiều tiền đến thế để", label: "BLUE" },
  { text: "Cậu có phiền nếu tui", label: "BLUE" },
  { text: "Để tui chỉ cho cậu thấy tại sao", label: "BLUE" },
  { text: "Tui nghĩ cậu nên hỏi ý", label: "BLUE" },
  { text: "Không thể có cái chuyện", label: "BLUE" },
  { text: "Cậu nói cứ như kiểu", label: "BLUE" },
  { text: "Cậu không thấy tụi nó cứ", label: "BLUE" },
  { text: "Cậu thì lúc nào cũng", label: "BLUE" },
  { text: "Tui chẳng hiểu sao cậu cứ", label: "BLUE" },
  { text: "Tui thấy nó khá là", label: "BLUE" },
  { text: "Họ nhờ tui", label: "BLUE" },
  { text: "Trên mạng bây giờ tràn ngập", label: "BLUE" },
  { text: "Tui thực sự không biết cách để", label: "BLUE" },
  { text: "Tôi không thèm cái", label: "BLUE" },
  { text: "Mỗi khi", label: "BLUE" },
  { text: "Có tổng cộng", label: "BLUE" },
  { text: "Nó quá là liều để", label: "BLUE" },
  { text: "tui chẳng có gì phải hối hận cả", label: "BLUE" },

  // RED (Idioms & Nuance)
  { text: "Mật ngọt chết ruồi", label: "RED" },
  { text: "Có ai ở nhà không?", label: "RED" },
  { text: "Thời gian trôi nhanh thật!", label: "RED" },
  { text: "Có chuyện gì cậu muốn nói với tui không?", label: "RED" },
  { text: "Tui không có sự lựa chọn!", label: "RED" },
  { text: "Nó làm tui nổi hết cả da gà!", label: "RED" },
  { text: "Nhớ đến đúng giờ nha", label: "RED" },
  { text: "Cậu tới số rồi!!!", label: "RED" },
  { text: "Cho tui thêm 2 tuần đi", label: "RED" },
  { text: "Có gì alo tui!", label: "RED" },
  { text: "Đừng sợ!, có tui đây", label: "RED" },
  { text: "Cậu làm gì thì cậu tự biết!", label: "RED" },
  { text: "Không tin thì cậu đi mà hỏi họ!", label: "RED" },
  { text: "Đời là phù du!", label: "RED" },
  { text: "Cậu xem tui là loại người gì?!?", label: "RED" },
  { text: "Mai họ mới về lận", label: "RED" },
  { text: "Cậu có hiểu cậu đang nói cái gì không?!?", label: "RED" },
  { text: "Dụ đó sao rồi?", label: "RED" },
  { text: "Giữ liên lạc nha!", label: "RED" },
  { text: "Cậu không ngồi yên được à?", label: "RED" },
  { text: "Cái gì cũng có cái giá của nó", label: "RED" },
  { text: "Đổ thêm dầu vào lửa", label: "RED" },
  { text: "Thật là lố bịch!", label: "RED" },
  { text: "trong gang tấc", label: "RED" },

  // PINK (Key Terms)
  { text: "Dép lào", label: "PINK" },
  { text: "Tham lam", label: "PINK" },
  { text: "Qúa rõ ràng", label: "PINK" },
  { text: "Khui bia", label: "PINK" },
  { text: "Dùng một lần", label: "PINK" },
  { text: "Tẩy não", label: "PINK" },
  { text: "Trì hoãn dự án", label: "PINK" },
  { text: "Kêu gọi tẩy chay", label: "PINK" },
  { text: "Mất bình tĩnh", label: "PINK" },
  { text: "Cố tình", label: "PINK" },
  { text: "Mưa lớn", label: "PINK" },
  { text: "Còn sống", label: "PINK" },
  { text: "Ói", label: "PINK" },
  { text: "Mãn tính", label: "PINK" },
  { text: "Bà bầu", label: "PINK" },
  { text: "Xếp hàng", label: "PINK" },
  { text: "Lên cân", label: "PINK" },
  { text: "Không thể tránh khỏi", label: "PINK" },
  { text: "Bỏ việc", label: "PINK" },
  { text: "Cố chấp", label: "PINK" },
  { text: "Lời dèm pha", label: "PINK" },
  { text: "Tiền nào của đó thôi", label: "PINK" },
  { text: "mất mạng", label: "PINK" },
  { text: "khoảnh khắc hiểm nghèo nhất", label: "PINK" }
];